"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.dateFormats = void 0;
exports.dateFormats = {
    LT: 'LT',
    LTS: 'LTS',
    LL: 'LL',
    ll: 'll',
    LLL: 'LLL',
    lll: 'lll',
    LLLL: 'LLLL',
    llll: 'llll',
    YY: 'YY',
    YYYY: 'YYYY',
    D: 'D',
    Do: 'Do',
    DD: 'DD',
    M: 'M',
    Mo: 'Mo',
    MM: 'MM',
    MMM: 'MMM',
    MMMM: 'MMMM',
    d: 'd',
    dd: 'dd',
    ddd: 'ddd',
    dddd: 'dddd',
    YYYYMMDD: 'YYYYMMDD',
    'MM/DD/YYYY': 'MM/DD/YYYY',
    'DD/MM/YYYY': 'DD/MM/YYYY',
    'DD-MM-YYYY': 'DD-MM-YYYY',
    'YYYY-MM-DD': 'YYYY-MM-DD',
    'YYYY/MM/DD': 'YYYY/MM/DD',
    'DD-MMM-YYYY': 'DD-MMM-YYYY',
    'DD MMM YYYY': 'DD MMM YYYY',
    'DD MMM YY': 'DD MMM YY',
    'MMM DD, YYYY': 'MMM DD, YYYY',
    'MMM DD': 'MMM DD',
    'DD MMM': 'DD MMM',
    'MMM YY': 'MMM YY',
    'MM/YYYY': 'MM/YYYY',
    'DD-MMM-YYYY hh:mm A': 'DD-MMM-YYYY hh:mm A',
    'DD/MM/YYYY hh:mm:ss A': 'DD/MM/YYYY hh:mm:ss A',
    'DD MMM hh:mm A': 'DD MMM hh:mm A',
    'hh:mm A DD MMM YYYY': 'hh:mm A DD MMM YYYY',
    'hh:mm A': 'hh:mm A',
    'YYYY-MM-DDTHH:mm:ss': 'YYYY-MM-DDTHH:mm:ss',
    'MM-DD-YYYY': 'MM-DD-YYYY',
};
//# sourceMappingURL=DateFormats.js.map