export declare const dateFormats: {
    LT: string;
    LTS: string;
    LL: string;
    ll: string;
    LLL: string;
    lll: string;
    LLLL: string;
    llll: string;
    YY: string;
    YYYY: string;
    D: string;
    Do: string;
    DD: string;
    M: string;
    Mo: string;
    MM: string;
    MMM: string;
    MMMM: string;
    d: string;
    dd: string;
    ddd: string;
    dddd: string;
    YYYYMMDD: string;
    'MM/DD/YYYY': string;
    'DD/MM/YYYY': string;
    'DD-MM-YYYY': string;
    'YYYY-MM-DD': string;
    'YYYY/MM/DD': string;
    'DD-MMM-YYYY': string;
    'DD MMM YYYY': string;
    'DD MMM YY': string;
    'MMM DD, YYYY': string;
    'MMM DD': string;
    'DD MMM': string;
    'MMM YY': string;
    'MM/YYYY': string;
    'DD-MMM-YYYY hh:mm A': string;
    'DD/MM/YYYY hh:mm:ss A': string;
    'DD MMM hh:mm A': string;
    'hh:mm A DD MMM YYYY': string;
    'hh:mm A': string;
    'YYYY-MM-DDTHH:mm:ss': string;
    'MM-DD-YYYY': string;
};
